Initial commit
monicah79/my-personal-portfolio pull request #11
Opened 2022-11-04 09:29 UTC by monicah79

- Updated desk version
- Edited index.html
- Updated style.css
- Followed figma design

2022-11-04 10:52 UTC, frank1738 requested changes
Hi @monicah79 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/1xVbRS6j52YSzp9P7N/giphy.gif"/>




## Highlights

✅ No linter error
✅ README is okay
✅ Good PR Description 👍 
## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 10:52 UTC, frank1738 commented on index.html
>              <a class="logo" href="">My Logo</a>
- [ ] I noticed your headline section of the desktop version still displays the mobile version. The hamburger button is not supposed to be visible on the desktop version. Kindly try as much as you can to match the original design. Work on the padding and positioning of elements. Also Kindly provide your plan with background images.

![image](https://user-images.githubusercontent.com/98453979/199952357-aea54096-fa9b-425c-b919-7d12f9c3758c.png)


![image](https://user-images.githubusercontent.com/98453979/199950989-86b511cc-fa21-4c45-a55a-000e42c5881e.png)

### Checkout Figma

![image](https://user-images.githubusercontent.com/98453979/199951290-ccb75cc3-225d-41b1-99f0-aa163697f25c.png)

- [ ] Your project cards look good but kindly reduce their sizes to match the Figma design. Also, implement the `hover` action on the buttons

![image](https://user-images.githubusercontent.com/98453979/199951973-8fb5f041-0437-4255-aa1b-5b967ba6dd95.png)

### Checkout Figma

![image](https://user-images.githubusercontent.com/98453979/199952120-878dc904-ee8e-40ab-a35e-d1525086b1ce.png)

2022-11-04 10:52 UTC, frank1738 commented on index.html
>  <p class="homepage-quotes">
- [ ] On your about section, Kindly reduce the width of the `description` so that the content on the right side would fit properly.

![image](https://user-images.githubusercontent.com/98453979/199953537-378a5962-349c-4aaa-b54b-591fc749610e.png)

### Checkout Figma

![image](https://user-images.githubusercontent.com/98453979/199953731-010b35c1-a537-4cf2-9be0-5b27fbe00c8f.png)

2022-11-04 10:52 UTC, frank1738 commented on index.html
>      <div class="sub-column">
- [ ] On your `contact section`, Kindly reduce the width of the paragraph text and also position the `get in touch` button to the center to match the original design.

![image](https://user-images.githubusercontent.com/98453979/199954672-5c069266-7f32-44c3-bbc8-7c23576d4bd5.png)

### Checkout Figma design

![image](https://user-images.githubusercontent.com/98453979/199954809-728213eb-12db-498e-9d83-e659aa12ea00.png)

2022-11-05 02:22 UTC, BregornOriginal approved these changes
Hi @monicah79 ,
Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳 🥳 🥳
Congratulations! 

## Highlights

✅ Linters are passing
✅ Correct use of GitHub Flow
✅ Good README
✅ Nice commit history

## Optional suggestions

![giphy](https://user-images.githubusercontent.com/93630700/200096936-71031266-19ab-4447-8b50-fb82a8bae43e.gif)

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2022-11-05 02:23 UTC, merged