My advanced portfolio
monicah79/my-personal-portfolio pull request #7
Opened 2022-10-28 12:45 UTC by monicah79

- Updated my index.html
- Added more styling in style.css
- Followed figma design

2022-10-28 15:46 UTC, Owusu-Desmond requested changes
Hi @monicah79  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/cYaB1VycDbOyOiXcCx/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> +        <img src="Images/snaps-portfolio.png" alt="">
- [ ] Please you should not have the `alt` attribute empty for your images. You should add a descriptive `alt` attribute to your images. :pray:

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> +        <li><img src="Images/Counter.png" alt=""></li>
- [ ] Please I suggest you should not have the `alt` attribute empty for your images. You should add a descriptive `alt` attribute to your images for accessibility reasons :pray:

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> +        <img src="Images/snaps-calender.png" alt="">
- [ ] Please I suggest you should not have the `alt` attribute empty for your images. You should add a descriptive `alt` attribute to your images for accessibility reasons :pray:

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> +        <li><img src="Images/Counter.png" alt=""></li>
- [ ] Please I suggest you should not have the `alt` attribute empty for your images. You should add a descriptive `alt` attribute to your images for accessibility reasons :pray:

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> +    </button>
- [ ] Please make sure your see project button follows the button styling: Active, Hover and Pressed to make it interactive. :pray:
 
For instance, 
 
   - You can change the background color, increase the size of the button, and change the color of the text when the user hovers over the button. You can visit [this link](https://www.w3schools.com/css/css3_buttons.asp) to learn more about it. :pray:
  
   - You can give it a `cursor: pointer` property to change the cursor to a pointer when the user hovers over it. You can read more about it [here](https://www.w3schools.com/cssref/pr_class_cursor.asp) :pray:

![Screenshot from 2022-10-28 15-23-58](https://user-images.githubusercontent.com/92303891/198674464-f1da08ad-9a4f-4397-9118-4cd7fed33450.png)

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> +    </button>
- [ ] Please make sure your see project button follows the button styling: Active, Hover and Pressed to make it interactive. :pray:
 
For instance, 
 
   - You can change the background color, increase the size of the button, and change the color of the text when the user hovers over the button. You can visit [this link](https://www.w3schools.com/css/css3_buttons.asp) to learn more about it. :pray:
  
   - You can give it a `cursor: pointer` property to change the cursor to a pointer when the user hovers over it. You can read more about it [here](https://www.w3schools.com/cssref/pr_class_cursor.asp) :pray:

![Screenshot from 2022-10-28 15-23-58](https://user-images.githubusercontent.com/92303891/198674464-f1da08ad-9a4f-4397-9118-4cd7fed33450.png)

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> +    </button>
- [ ] Please make sure your see project button follows the button styling: Active, Hover and Pressed to make it interactive. :pray:
 
For instance, 
 
   - You can change the background color, increase the size of the button, and change the color of the text when the user hovers over the button. You can visit [this link](https://www.w3schools.com/css/css3_buttons.asp) to learn more about it. :pray:
  
   - You can give it a `cursor: pointer` property to change the cursor to a pointer when the user hovers over it. You can read more about it [here](https://www.w3schools.com/cssref/pr_class_cursor.asp) :pray:

![Screenshot from 2022-10-28 15-23-58](https://user-images.githubusercontent.com/92303891/198674464-f1da08ad-9a4f-4397-9118-4cd7fed33450.png)

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> + </button>
- [ ] Please make sure your see project button follows the button styling: Active, Hover and Pressed to make it interactive. :pray:
 
For instance, 
 
   - You can change the background color, increase the size of the button, and change the color of the text when the user hovers over the button. You can visit [this link](https://www.w3schools.com/css/css3_buttons.asp) to learn more about it. :pray:
  
   - You can give it a `cursor: pointer` property to change the cursor to a pointer when the user hovers over it. You can read more about it [here](https://www.w3schools.com/cssref/pr_class_cursor.asp) :pray:

![Screenshot from 2022-10-28 15-33-11](https://user-images.githubusercontent.com/92303891/198676361-695b835a-fcdd-4c43-9b23-3118ff935d53.png)

2022-10-28 15:46 UTC, Owusu-Desmond commented on index.html
> +        </li>
- [ ] Please you should only use the `ul` to wrap your list items `li` in your project. But you have used the `div` tag to wrap the `li` tag in your project. You can read more about it [here](https://www.w3schools.com/html/html_lists.asp) :pray:

2022-10-28 19:21 UTC, OyePriscilla requested changes
## Hi @monicah79   😄 ,
Honestly, you've done a great work 🤝, but there are few issues to rectify. Be encouraged, you're almost there. 👍 

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
 
## (Highlights) Good Points: 
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* PR has a good title :heavy_check_mark:

## (Changes Required) 

- [ ] Please I just noticed that you first section is not rendered properly.

## Your design

![crr17](https://user-images.githubusercontent.com/103386183/198715494-3b5e28dc-c626-429e-80b2-dd3556670ff6.png)

- [ ] Take note of other changes required from the inline comments as well 👍 

 
## [Optional] suggestions:
 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
**Cheers and Happy coding! :clap::clap::clap:**
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear
Please, remember to tag @oyepriscilla in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-28 19:21 UTC, OyePriscilla commented on index.html
> +    <div class="sub-column">
- [ ] Please kindly wrap the list of your technology with `ul` as the first reviewer suggested. 🙏 `ul` has semantics, `div` is just an ordinary container.

2022-10-28 19:21 UTC, OyePriscilla commented on index.html
> +    Get My Resume
- [ ] Kindly please ensure to add button styling as the first reviewer suggested. 🙏 

## Illustration of what you should do:
.button:hover {
  background-color: #color according to template; 
  color: white;
}

- [ ] Please do the same for active and pressed styling as well. :smile

2022-10-28 19:29 UTC, monicah79 commented
Thanks for the feedback! but when i add ul its disorganising my work ,,,how
do i add ul ,,,outside a div or inside

On Fri, 28 Oct 2022 at 22:21, Oyebade Priscilla ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @monicah79 <https://github.com/monicah79> 😄 ,
>
> Honestly, you've done a great work 🤝, but there are few issues to
> rectify. Be encouraged, you're almost there. 👍
>
>
> <https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966>
> (Highlights) Good Points:
>
>    - No linter errors. ✔️
>    - Followed Github flow ✔️
>    - PR has a good title ✔️
>
> (Changes Required)
>
>    - Please I just noticed that you first section is not rendered
>    properly.
>
> Your design
>
> [image: crr17]
> <https://user-images.githubusercontent.com/103386183/198715494-3b5e28dc-c626-429e-80b2-dd3556670ff6.png>
>
>    - Take note of other changes required from the inline comments as well
>    👍
>
> [Optional] suggestions:
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> *Cheers and Happy coding! 👏👏👏*
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear
> Please, remember to tag @OyePriscilla <https://github.com/OyePriscilla>
> in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
> ------------------------------
>
> In index.html
> <https://github.com/monicah79/my-personal-portfolio/pull/7#discussion_r1008370250>
> :
>
> > +        <a href=""><img src="Images/medium.svg" alt="medium icon"></a>
>
> +    </li>
>
> +    <li>
>
> +        <a href=""><img src="Images/twitter.svg" alt="twitter icon"></a>
>
> +    </li>
>
> +    <li>
>
> +        <a href=""><img src="Images/Angel-list.svg" alt="Angel-list icon"></a>
>
> +    </li>
>
> +</ul>
>
> +<button class="sub-button">
>
> +    Get My Resume
>
> + </button>
>
> +
>
> +</section>
>
> +<section class="sub-language">
>
> +    <div class="sub-column">
>
>
>
>    - Please kindly wrap the list of your technology with ul as the first
>    reviewer suggested. 🙏 ul has semantics, div is just an ordinary
>    container.
>
> ------------------------------
>
> In index.html
> <https://github.com/monicah79/my-personal-portfolio/pull/7#discussion_r1008374893>
> :
>
> > +<button class="sub-button">
>
> +    Get My Resume
>
>
>
>    - Kindly please ensure to add button styling as the first reviewer
>    suggested. 🙏
>
> Illustration of what you should do:
>
> .button:hover {
> background-color: #color according to template;
> color: white;
> }
>
>    - Please do the same for active and pressed styling as well. :smile
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/monicah79/my-personal-portfolio/pull/7#pullrequestreview-1160527488>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZTUWS7E4JSAXU3LHQKMFH3WFQRVFANCNFSM6AAAAAARRBIDH4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-28 20:21 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @monicah79 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights :heavy_check_mark: 
:white_check_mark:  No Linters error
:white_check_mark: Descriptive pull request
:white_check_mark: Great working on the set up the project 
:white_check_mark: Good commit messages 
:white_check_mark: Professional README file

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 20:25 UTC, merged

2022-10-29 06:39 UTC, OyePriscilla commented
Hi @monicah79, I apologise for the late response. I am glad your work is approved; be determined and keep moving. You can do it 👍 👍